export const SONGS = [
    {
        id: 10,
        name: 'Panic Room',
        src: 'Au_Ra & CamelPhat - Panic Room',
        artist: 1,
        artists: 'Au_Ra, Camelphat'
    },
    {
        id: 11,
        name: 'Without You Audio ft. Sandro Cavazza',
        src: 'Avicii - Without You Audio ft. Sandro Cavazza',
        artist: 3,
        artists: 'Avicci, Sandro Cavazza'
    },
    {
        id: 12,
        name: 'Baian (Jack Back Remix)',
        src: 'Barbatuques - Baian (Jack Back Remix)',
        artist: 5,
        artists: 'Barbatuques, Jack Back',
    },
    {
        id: 13,
        name: 'The Sign',
        src: 'CamelPhat & Anyma - The Sign',
        artist: 1,
        artists: 'Camelphat, Anyma',
    },
    {
        id: 14,
        name: 'Breathe (ft. Jem Cooke)',
        src: 'CamelPhat & Cristoph - Breathe (ft. Jem Cooke)',
        artist: 1,
        artists: 'Camelphat, Cristoph, Jem Cooke',
    },
    {
        id: 15,
        name: 'Cola',
        src: 'Camelphat & Elderbrook - Cola',
        artist: 1,
        artists: 'Camelphat, Elderbrook'
    },
    {
        id: 16,
        name: 'For a Feeling',
        src: 'CamelPhat x ARTBAT - For A Feeling (ft. Rhodes)',
        artist: 1,
        artists: 'Camelphat, ARTBAT, Rhodes'
    },
    {
        id: 17,
        name: 'Just a Little More Love (feat. Chris Willis) (Jack Back 2018 Remix)',
        src: 'David Guetta - Just a Little More Love (feat. Chris Willis) (Jack Back 2018 Remix)',
        artist: 5,
        artists: 'David Guetta, Chriss Willis, Jack Back'
    },
    {
        id: 18,
        name: 'All For Love ft. Sandro Cavazza',
        src: 'Felix Jaehn - All For Love ft. Sandro Cavazza',
        artist: 3,
        artists: 'Felix Jaehn, Sandro Cavazza',
    },
    {
        id: 19,
        name: 'Delilah (pull me out of this)',
        src: 'Fred again.. - Delilah (pull me out of this)',
        artist: 0,
        artists: 'Fred again..',
    },
    {
        id: 20,
        name: 'Marea (We’ve Lost Dancing)',
        src: 'Fred again.. feat. The Blessed Madonna - Marea (We’ve Lost Dancing)',
        artist: 0,
        artists: 'Fred again.., The Blessed Madonna',
    },
    {
        id: 21,
        name: 'Turn On The Lights again.. (feat. Future)',
        src: 'Fred again.. x Swedish House Mafia - Turn On The Lights again.. (feat. Future)',
        artist: 0,
        artists: 'Fred again.., Swedish House Mafia, Future',
    },
    {
        id: 22,
        name: 'Baby again',
        src: 'Fred again.., Skrillex, Four Tet - Baby again',
        artist: 0,
        artists: 'Fred again.., Skrillex, Four Tet',
    },
    {
        id: 23,
        name: '(It Happens) Sometimes',
        src: 'Jack Back - (It Happens) Sometimes',
        artist: 5,
        artists: 'Jack Back',
    },
    {
        id: 24,
        name: 'Survivor',
        src: 'Jack Back - Survivor',
        artist: 5,
        artists: 'Jack Back',
    },
    {
        id: 25,
        name: 'Case Of The Ex feat. Mya Francis',
        src: 'Jack Back & NFI - Case Of The Ex feat. Mya Francis',
        artist: 5,
        artists: 'Jack Back, NFI, Mya Francis',
    },
    {
        id: 26,
        name: 'Happy Now ft. Sandro Cavazza',
        src: 'Kygo - Happy Now ft. Sandro Cavazza',
        artist: 3,
        artists: 'Kygo, Sandro Cavazza',
    },
    {
        id: 27,
        name: 'Forever Yours (Avicii Tribute)',
        src: 'Kygo, Avicii, Sandro Cavazza - Forever Yours (Avicii Tribute)',
        artist: 3,
        artists: 'Kygo, Avicci, Sandro Cavazza',
    },
    {
        id: 28,
        name: "I'll Wait",
        src: "Kygo, Sasha Alex Sloan - I'll Wait",
        artist: 2,
        artists: 'Kygo, Sasha Alex Sloan',
    },
    {
        id: 29,
        name: "Lean On Me",
        src: "Sandro Cavazza - Lean On Me",
        artist: 3,
        artists: 'Sandro Cavazza',
    },
    {
        id: 30,
        name: "Dancing With Your Ghost",
        src: "Sasha Alex Sloan - Dancing With Your Ghost",
        artist: 2,
        artists: 'Sasha Alex Sloan',
    },
    {
        id: 31,
        name: "Is It Just Me ft. Charlie Puth",
        src: "Sasha Alex Sloan - Is It Just Me ft. Charlie Puth",
        artist: 2,
        artists: 'Sasha Alex Sloan, Charlie Puth',
    },
    {
        id: 32,
        name: "Older",
        src: "Sasha Alex Sloan - Older",
        artist: 2,
        artists: 'Sasha Alex Sloan',
    },
    {
        id: 33,
        name: "when was it over ft. Sam Hunt",
        src: "Sasha Alex Sloan - when was it over ft. Sam Hunt",
        artist: 2,
        artists: 'Sasha Alex Sloan, Sam Hunt',
    },
    {
        id: 34,
        name: "Rumble",
        src: "Skrillex, Fred again.. & Flowdan - Rumble",
        artist: 0,
        artists: 'Skrillex, Fred again.., Flowdan',
    },
    {
        id: 35,
        name: "Come Together",
        src: "The Beatles - Come Together",
        artist: 4,
        artists: 'The Beatles',
    },
    {
        id: 36,
        name: "Here Comes The Sun",
        src: "The Beatles - Here Comes The Sun",
        artist: 4,
        artists: 'The Beatles',
    },
    {
        id: 37,
        name: "Let It Be",
        src: "The Beatles - Let It Be",
        artist: 4,
        artists: 'The Beatles',
    },
    {
        id: 38,
        name: "Twist And Shout",
        src: "The Beatles - Twist And Shout",
        artist: 4,
        artists: 'The Beatles',
    },
    {
        id: 39,
        name: "Yesterday",
        src: "The Beatles - Yesterday",
        artist: 4,
        artists: 'The Beatles',
    },
]